# 객체지향(Object Oriented) 프로그래밍
## 메소드(Method)
- 메서드(Method)는 클래스 바디 안에서 정의되는 함수입니다. 
- 클래스의 인스턴스의 어트리뷰트(attribute)로서 호출되면, 그 메서드는 첫 번째 인자로 인스턴스 객체(self)를 받습니다. 
- 첫 번째 인자를 설정 안 하면 에러가 발생합니다. 이 첫 번째 인자를 ‘self’라고 씁니다. 
```
class ClassName:
    def method_name(self):
    method_body

    class_body
```

## 속성(Attribute)
- 클래스 속성(Attribute)를 만들 때는 _  _ _init_ _  _메서드 안에서 self.속성에 값을 할당하면 됩니다.
```
class ClassName:
    def __init__(self):
    self.속성 = 값
```
## _  _ _init_ _ _ 메서드
- _  _ _init_ _  _ 메서드는 james = Person()처럼 클래스에 소괄호(())를 붙여서 인스턴스를 만들 때 호출되는 특별한 메서드(special method, magic method)입니다.
- _  _ _init_ _  _은 initialize의 줄임말로 인스턴스(객체)를 초기화(메모리에 공간을 할당하고 값을 부여함)합니다.
- 밑줄 두개(__ double under, 던더)가 양 옆으로 붙어있는 메서드는 파이썬이 자동으로 호출하는 메서드입니다. 
- 스페셜 메서드(special method) 혹은 매직 메서드(magic method)라고 부릅니다. 던더 메서드로 불리기도 합니다. 
- 파이썬의 여러 가지 기능을 사용할 때 이 던더 메서드를 구현하는 식으로 사용하게 됩니다.
- **속성은 _  _ _init_ _  _ 메서드에서 만든다는 점**과 **self에 마침표(.)를 붙여 속성명을 붙이고 값을 할당하는 점**을 기억해두세요.
```
class Person:
    def __init__(self):
        self.hello = "안녕하세요."
        
    def greeting(self):
        print(self.hello)
    
```
## self 란??
- self는 인스턴스 자기 자신을 의미합니다.
- 위 예제에서 인스턴스가 생성될 때 self.hello = ‘안녕하세요’ 처럼 자기 자신에 속성을 추가하여 사용했었습니다.
- _  _ _init_ _  _의 매개변수 self에 들어가는 값는 Person() 인스턴스라고 할 수 있습니다.
- self가 완성된 후에는 변수인 james에 할당되었습니다.
- 이후 메서드를 호출하면 현재 인스턴스가 자동으로 매개변수 self에 들어옵니다. 
- 그래서 greeting 메서드에서 print(self.hello)처럼 속성을 출력할 수 있었습니다.

### 예제

In [1]:
class Student():
    pass

In [2]:
stu_a=Student() # 클래스로부터 인스턴스 초기화 
stu_b=Student()

In [3]:
stu_a.hello="안녕하세요"

In [4]:
print(stu_a.hello)

안녕하세요


In [5]:
print(stu_b.hello) # a와 b는 서로 다른 인스턴스

AttributeError: 'Student' object has no attribute 'hello'

In [6]:
class Student():
    def __init__(self):
        self.hello="안녕"
stu_a=Student()
stu_b=Student()
print(stu_a.hello)
print(stu_b.hello)

안녕
안녕


In [7]:
class Student():
    def __init__(self,name):
        self.hello="안녕"
        self.name=name
stu_a=Student('kyeongmo')
stu_b=Student('miranda')
print(stu_a.name)
print(stu_b.name)

kyeongmo
miranda


In [19]:
class Student():
    def __init__(self,name,age):
        self.hello="안녕"
        self.name=name
        self.age=age
    def introduce(self):
        print(self.hello)
        print(f'내 이름은 {self.name}야')
        print(f'내 나이는 {self.age}살 이야')
        
stu_a=Student('kyeongmo',40)
stu_b=Student('miranda',50)

print(stu_a.introduce())

print(stu_b.introduce())

안녕
내 이름은 kyeongmo야
내 나이는 40살 이야
None
안녕
내 이름은 miranda야
내 나이는 50살 이야
None


In [21]:
# __dict__ 는 인스턴스의 속성을 볼 수 있음
stu_a.__dict__

{'hello': '안녕', 'name': 'kyeongmo', 'age': 40}

In [24]:
class Person2:
    def __init__(self, name, age, address):
        self.hello='안녕'
        self.name=name
        self.age=age
        self.address=address
        
    def greeting(self):
        print(f'{self.hello} 제 이름은 {self.name}입니다.')

In [25]:
maria=Person2('마리아',23,'서울시 마포구')
maria.greeting()

안녕 제 이름은 마리아입니다.


In [34]:
class Person:
    def __init__(self, name, age, address):
        self.hello='안녕'
        self.name=name
        self.age=age
        self.address=address
        
name=input('이름은 무엇인가요?: ')
age=input('나이는 무엇인가요?: ')
address=input('주소는 무엇인가요?: ')
Person_1=Person(name,age,address)

name=input('이름은 무엇인가요?: ')
age=input('나이는 무엇인가요?: ')
address=input('주소는 무엇인가요?: ')
Person_2=Person(name,age,address)


print(f'첫번째 이름: {Person_1.name}')
print(f'첫번째 나이: {Person_1.age}')
print(f'첫번째 주소: {Person_1.address}')

print(f'두번째 이름: {Person_2.name}')
print(f'두번째 나이: {Person_2.age}')
print(f'두번째 주소: {Person_2.address}')


    
    

이름은 무엇인가요?:  마리아
나이는 무엇인가요?:  20
주소는 무엇인가요?:  서울시강남구
이름은 무엇인가요?:  제임스
나이는 무엇인가요?:  21
주소는 무엇인가요?:  서울시 구로구


첫번째 이름: 마리아
첫번째 나이: 20
첫번째 주소: 서울시강남구
두번째 이름: 제임스
두번째 나이: 21
두번째 주소: 서울시 구로구


## 비공개 속성 사용하기

In [37]:
class Person3:
    def __init__(self, name, age, address,wallet):
        self.hello='안녕'
        self.name=name
        self.age=age
        self.address=address
        self.__wallet=wallet # 비공개 속성은 밖에서 접근이 불가능
        
    def greeting(self):
        print(f'{self.hello} 제 이름은 {self.name}입니다.')

In [38]:
hkm=Person3('허경모',27,'인천 서구',20000)

In [39]:
print(hkm.wallet)

AttributeError: 'Person3' object has no attribute 'wallet'

In [40]:
print(hkm.__wallet)

AttributeError: 'Person3' object has no attribute '__wallet'

In [43]:
class Person4:
    def __init__(self, name, age, address,wallet):
        self.hello='안녕'
        self.name=name
        self.age=age
        self.address=address
        self.__wallet=wallet # 비공개 속성은 밖에서 접근이 불가능
        
    def greeting(self):
        print(f'{self.hello} 제 이름은 {self.name}입니다.')

# 메소드를 이용하여 접근이 가능
    def amount(self):
        print(self.__wallet)

In [44]:
hkm=Person4('허경모',27,'인천 서구',20000)
hkm.amount()

20000


In [45]:
class Person5:
    def __init__(self, name, age, address,wallet):
        self.hello='안녕'
        self.name=name
        self.age=age
        self.address=address
        self.__wallet=wallet # 비공개 속성은 밖에서 접근이 불가능
    
    def pay(self,amount):
        if self.__wallet < amount:
            print('돈이 모자랍니다.')
            return 
        self.__wallet -= amount
        print(f'{self.__wallet}원 남았습니다.')

In [46]:
hkm=Person5('허경모',27,'인천 서구',20000)
hkm.pay(10000)

10000원 남았습니다.


In [50]:
health, mana, ap= map(float,input('체력, 마나, AP를 입력하세요.').split(' '))

class Annie:
    def __init__(self,health,mana,ap):
        self.healht=health
        self.mana=mana
        self.ap=ap
        
    def tibbers(self):
        print(f'티버: 피해량: {self.ap*0.65 + 400}')
        
annie=Annie(health,mana,ap)
annie.tibbers()

체력, 마나, AP를 입력하세요. 511.68 334.0 298


티버: 피해량: 593.7


In [3]:
class Person5:
    def __init__(self, name, age, address,wallet):
        self.hello='안녕'
        self.name=name
        self.age=age
        self.address=address
        self.__wallet=wallet # 비공개 속성은 밖에서 접근이 불가능
    
    def pay(self,amount):
        if self.__wallet < amount:
            print('돈이 모자랍니다.')
            return 
        self.__wallet -= amount
        print(f'{self.__wallet}원 남았습니다.')
        
    @classmethod # cls 자체가 인자가 됨
    def from_string(cls,string):
        name,age,address,__wallet = string.split(',')
        return cls(name, age, address, __wallet)
    


# Numpy
## 넘파이 배열
- 배열(Array)란 **순서**가 있는 **같은 종류(type)의 데이터**가 저장되는 자료형
- 요소의 개수를 바꿀 수 없음
- 리스트(list)보다 넘파이 배열이 구조적으로 속도가 빠르고 메모리를 더 적게 사용

In [2]:
import numpy as np

### 1차원 배열 만들기

In [3]:
ar=np.array([i for i in range(10)])
ar

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
ar.shape

(5,)

In [13]:
ar.dtype

dtype('float64')

In [10]:
ar2=np.array([0.1, 5, 2, 12, 0.5])
ar2

array([ 0.1,  5. ,  2. , 12. ,  0.5])

In [11]:
ar2.shape

(5,)

In [12]:
ar2.dtype

dtype('float64')

In [16]:
ar3=np.array([i for i in range(3,10,3)])
ar3

array([3, 6, 9])

### 넘파이의 자료형
- 배열 생성시 dtype으로 지정
- 숫자는 생략 가능
- 유니코드 문자열은 U1~8

In [29]:
ar4=np.array([ i for i in range(2,10,2)],'f')
print(ar4)
print(ar4.dtype)

[2. 4. 6. 8.]
float32


In [22]:
ar5 = np.array(['가나다라마 ' for i in range(5)],'U8')
print(ar5)
print(ar5.dtype)
# <U8은 최대 8글자의 유니코드 자료형이다.
# 시퀀스 자료형 중 제일 큰 값이 <U5이지만 <U8로 타입이 지정되었다.

['가나다라마 ' '가나다라마 ' '가나다라마 ' '가나다라마 ' '가나다라마 ']
<U8


In [31]:
x=np.array([1,2,3],dtype='f')
x.dtype

dtype('float32')

In [32]:
x[0]+x[1]

3.0

In [33]:
x=np.array([1,2,3],dtype="U")
x.dtype

dtype('<U1')

In [34]:
x[0]+x[1]

'12'

- 무한대를 표현하기 위한 np.inf
- 정의할 수 없는 숫자를 나타내는 np.nan

### 벡터화 연산
- 배열의 각 요소에 대한 반복 연산을 하나의 명령어로 처리하는 '벡터화 연산' 
- 벡터화 연산을 사용하면 for 반복문 없이 간단하게 단 한번의 연산식으로 표현 가능

In [39]:
data = [0,1,2,3,4,5,6,7,8,9]
answer = [d*2 for d in data]
answer

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [36]:
x=np.array(data)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [37]:
2*x

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [47]:
list_samp=[i for i in range(3)]
print(list_samp * 5)

[0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2]


In [48]:
arr_list_samp=np.array(list_samp)
print(arr_list_samp*5)

[ 0  5 10]


- 비교연산과 논리 연산을 포함한 모든 종류의 수학 연산에 대해 적용됨

In [42]:
a= np.array([1,2,3])
b=np.array([10,20,30])

In [43]:
2*a+b

array([12, 24, 36])

In [44]:
a == 2

array([False,  True, False])

In [45]:
b > 10

array([False,  True,  True])

In [46]:
(a==2)&(b>10)

array([False,  True, False])

### 2차원 배열(Matrix) 만들기

In [49]:
c= np.array([[0,1,2],[3,4,5]])
c

array([[0, 1, 2],
       [3, 4, 5]])

In [50]:
c.shape

(2, 3)

In [51]:
len(c)

2

In [52]:
len(c[0])

3

In [81]:
arr=np.array([[10,20,30,40],[50,60,70,80]])
arr

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

### 3차원 배열 만들기
- 깊이 x 행 x 열

In [59]:
a=np.array([[[1,2,3,4],[5,6,7,8],[9,10,11,12]],[[13,14,15,16],[17,18,19,20],[21,22,23,24]]])
a

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

### 배열의 차원과 크기 알아내기
- 배열.ndim -> 배열의 차원 
- 배열.shape -> 배열의 크기

In [61]:
a.ndim

3

In [62]:
a.shape

(2, 3, 4)

### 배열의 인덱싱
#### 1차원 배열

In [63]:
a=np.array([i for i in range(5)])
a

array([0, 1, 2, 3, 4])

In [64]:
a[2]

2

In [65]:
a[-1]

4

#### 2차원 배열
- 콤마(,)를 사용하여 접근(행,열)
- 콤마로 구분된 차원을 축(axis)라고도 함
- 그래프의 x축과 y축을 떠올리면 됨

In [77]:
list_sample=[[1,2,3,4],[5,6,7,8]]
list_sample[1][1]

6

In [78]:
b=np.array(list_sample)
print(b)
b[1,1]

[[1 2 3 4]
 [5 6 7 8]]


6

- 다차원 배열 원소 중 복수 개를 접근하려면 슬라이싱과 콤마를 함께 사용

In [79]:
b[0,:]

array([1, 2, 3, 4])

In [80]:
b[:,0]

array([1, 5])

In [82]:
b[1,1:]

array([6, 7, 8])

In [83]:
b[:2,:2]

array([[1, 2],
       [5, 6]])

In [85]:
b[:5,:5]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [95]:
# m=np.array([[0,1,2,3,4],[5,6,7,8,9],[10,11,12,13,14]])
m=np.array([i for i in range(15)]).reshape(3,5)
print(m)

print(m[1,2])
print(m[2,4]) # m[2,-1]
print(m[1,1:3])
print(m[1:3,2])
print(m[:2,3:5])

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
7
14
[6 7]
[ 7 12]
[[3 4]
 [8 9]]


### 배열 생성 메서드
- zeros, ones
- xeros_like, ones_like
- empty
- arange
- linspace, logspace

#### zeros
- 0으로 초기화된 배열 생성

In [96]:
a=np.zeros(5)
a

array([0., 0., 0., 0., 0.])

In [97]:
b=np.zeros((5,2),dtype='i')
b

array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0]], dtype=int32)

In [98]:
d=np.zeros(5,dtype='U4')
d

array(['', '', '', '', ''], dtype='<U4')

In [100]:
d[0]='abc'
d[1]='abcd'
d[2]='abcde' # 4글자 넘어서 짤림
d

array(['abc', 'abcd', 'abcd', '', ''], dtype='<U4')

#### ones
- 0이 아닌 1로 초기화된 배열을 생성

In [102]:
a = np.ones((2,3,4),dtype='i8')
a

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int64)

#### ones_like / zeros_like
- 크기를 튜플로 명시하지 않고 **다른 배열과 같은 크기의 배열** 을 생성

In [103]:
b=np.ones_like(a,dtype='f')
b

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]], dtype=float32)

#### empty 
- 배열을 생성만 하고 특정한 값으로 초기화 하지 않음

In [105]:
g=np.empty((4,3))
g

array([[0.0078125, 0.0078125, 0.0078125],
       [0.0078125, 0.0078125, 0.0078125],
       [0.0078125, 0.0078125, 0.0078125],
       [0.0078125, 0.0078125, 0.0078125]])

#### arange 
- 넘파이의 range 명령
- 특정한 규칙에 따라 증가하는 수열 만듦

In [106]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [107]:
np.arange(3,21,2)

array([ 3,  5,  7,  9, 11, 13, 15, 17, 19])

#### linspace, logspace
- linspace(시,끝,n) -> 시작부터 끝까지 같은 간격으로 n만큼 나눠지도록 함

In [108]:
ex = np.linspace(0,100,20)
ex

array([  0.        ,   5.26315789,  10.52631579,  15.78947368,
        21.05263158,  26.31578947,  31.57894737,  36.84210526,
        42.10526316,  47.36842105,  52.63157895,  57.89473684,
        63.15789474,  68.42105263,  73.68421053,  78.94736842,
        84.21052632,  89.47368421,  94.73684211, 100.        ])

In [109]:
ex2=np.logspace(0,100,5)
ex2

array([1.e+000, 1.e+025, 1.e+050, 1.e+075, 1.e+100])

### 전치 연산 (x,y)->(y,x)

In [110]:
A=np.array([[1,2,3],[4,5,6]])
A

array([[1, 2, 3],
       [4, 5, 6]])

In [111]:
A.T

array([[1, 4],
       [2, 5],
       [3, 6]])

### 배열의 크기 변형 
#### reshpape(행,열)

In [114]:
ex=np.arange(12)
ex.reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [116]:
# -1를 넣으면 동적으로 사용 가능
ex.reshape(2,-1)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [119]:
ex.reshape(-1,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

#### flatten / ravel - 다차원 배열을 1차원으로 만들기

In [120]:
ex.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [121]:
ex.reshape(4,-1)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [124]:
ex.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

#### newaxis - 1차원 증가
- 같은 배열에 대해 차원만 1차원 증가시키는 경우에는 newaxis 명령을 사용하기도 함

In [150]:
x=np.arange(5)
x[:,np.newaxis]

array([[0],
       [1],
       [2],
       [3],
       [4]])

### 배열 연결

#### hstack
- 행의 수가 같은 두 개 이상의 배열을 옆으로 연결하여 열의 수가 더 많아진 배열을 만듦
- 연결할 배열은 하나의 리스트에 담아야 함

#### vstack
- 열의 수가 같은 두 개 이상의 배열을 위아래로 연결하여 행의 수가 더 많아진 배열을 만듦
- 연결할 배열은 하나의 리스트에 담아야 함 

In [127]:
b1=np.ones((2,3))
b2=np.zeros((3,3))

In [129]:
b3=np.vstack([b1,b2])
b3

array([[1., 1., 1.],
       [1., 1., 1.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [130]:
b3.shape

(5, 3)

#### dstack
- 깊이 방향으로 배열을 합침

In [131]:
c1=np.ones((3,4))
c1

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [132]:
c2=np.zeros((3,4))
c2

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [134]:
c3= np.dstack([c1,c2])
c3

array([[[1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.]],

       [[1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.]],

       [[1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.]]])

In [135]:
c3.shape

(3, 4, 2)

#### stack
- 사용자가 지정한 차원(축으로) 배열을 연결
- 디폴트 인수값은 axis=0이고 가장 앞쪽에 차원이 생성됨

In [137]:
c4=np.stack([c1,c2])
c4

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [138]:
c5=np.stack([c1,c2],axis=1)
c5

array([[[1., 1., 1., 1.],
        [0., 0., 0., 0.]],

       [[1., 1., 1., 1.],
        [0., 0., 0., 0.]],

       [[1., 1., 1., 1.],
        [0., 0., 0., 0.]]])

In [139]:
c6=np.stack([c1,c2],axis=2)
c6

array([[[1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.]],

       [[1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.]],

       [[1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.]]])

#### r_ 메서드
- hstack 명령과 비슷하게 배열을 좌우로 연결
- 다만 메서드임에도 불구하고 소괄호()를 사용하지 않고 인덱싱과 같이 **대괄호[]** 를 사용
- 이런 특수 메서드를 **인덱서**라고 함

In [140]:
np.r_[np.array([1,2,3]), np.array([4,5,6])]

array([1, 2, 3, 4, 5, 6])

#### c_ 메서드
- 배열의 차원을 증가시킨 후 좌우로 연결
- 만약 1차원 배열을 연결하면 2차원 배열이 됨

In [141]:
np.c_[np.array([1,2,3]),np.array([4,5,6])]

array([[1, 4],
       [2, 5],
       [3, 6]])

#### tile
- 동일한 배열을 반복하여 연결"

In [142]:
a=np.array([[0,1,2],[3,4,5]])
np.tile(a,2)

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5]])

In [144]:
np.tile(a,(3,2))

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5]])

In [148]:
arr1=np.array([0,0,0,1,1])
arr2=np.array([10,20,30,40,50])
arr3=arr2+50
arr4=arr3+50

arr5=np.vstack([arr1,arr1,arr1,arr2,arr3,arr4])
arr6=np.stack([arr5,arr5])
arr6

array([[[  0,   0,   0,   1,   1],
        [  0,   0,   0,   1,   1],
        [  0,   0,   0,   1,   1],
        [ 10,  20,  30,  40,  50],
        [ 60,  70,  80,  90, 100],
        [110, 120, 130, 140, 150]],

       [[  0,   0,   0,   1,   1],
        [  0,   0,   0,   1,   1],
        [  0,   0,   0,   1,   1],
        [ 10,  20,  30,  40,  50],
        [ 60,  70,  80,  90, 100],
        [110, 120, 130, 140, 150]]])