### 복습

```
현재까지 계산한 값을 속성 value로 갖는 계산기 클래스를 만들고자 합니다.
- value 속성의 초기값은 0으로 갖습니다.
- add 메서드는 value 값에 인수로 받은 값을 가산합니다.
- minus 메서드는 value 값에 인수로 받은 값을 감산합니다.
- show_value 메서드는 다음과 같이 현재 값을 출력합니다.
“현재 값은 000입니다.”
- add와 minus는 가변 인자를 활용하여 시퀀스도 처리합니다.
- 인수가 없는 경우 “숫자를 입력해주세요"라고 출력합니다.
- 숫자가 아닌 값에 대해서 처리는 따로 하지 않습니다.
```

In [254]:
import numpy as np
# np.sum 으로 해결 
class Calculator:
    def __init__(self):
        self.value=0
        
    def add(self,*numbers):
        if len(numbers)==0:
            print('숫자를 입력해주세요.')
        self.value += np.sum(numbers)
        
    def minus(self,*numbers):
        if len(numbers)==0:
            print('숫자를 입력해주세요.')
        self.value -= np.sum(numbers)
        
    def show_value(self):
        print(f'현재 값은 {int(self.value)}입니다.')

In [308]:
import numpy as np
# 반복문으로 해결
class Calculator:
    def __init__(self):
        self.value=0
        
    def add(self,*numbers):
        if len(numbers)==0:
            print('숫자를 입력해주세요.')
        for i in numbers:
            if type(i)==int:
                self.value += i
            else:
                self.value += sum(i)
        
    def minus(self,*numbers):
        if len(numbers)==0:
            print('숫자를 입력해주세요.')
        for i in numbers:
            if type(i)==int:
                self.value -= i
            else:
                self.value -= sum(i)
        
    def show_value(self):
        print(f'현재 값은 {int(self.value)}입니다.')

In [428]:
# 답안
import numpy as np
class  Calculator:
    def __init__(self):
        self.value=0
    
    def add(self, *number):
        if len(number)>0:
            num = np.array(number) # 시퀀스 안에 시퀀스가 여러 개 있으면 2차원 배열로 만들어짐 (튜플 안에 리스트)
            self.value += np.sum(num)
        else:
            print('숫자 입력')
            
    def minus(self, *number):
        if len(number) > 0:
            num = np.array(number)
            self.value -= np.sum(num)
        else:
            print('숫자 입력')
            
    def show_value(self):
        print(f'현재 값은 {self.value}입니다.')

In [429]:
c=Calculator()

In [430]:
c.add(100)

In [431]:
c.minus(20)

In [432]:
c.show_value()

현재 값은 80입니다.


In [433]:
c.add()

숫자 입력


In [434]:
c.minus([10,20])

In [435]:
c.show_value()

현재 값은 50입니다.


In [436]:
c.add(range(1,6))

In [437]:
c.show_value()

현재 값은 65입니다.


# Numpy

## 브로드캐스팅
- 모양이 다른 배열 간의 연산이 가능하도록 배열의 크기를 변환
- 더 작은 배열이 더 큰 배열에 호환되는 모양으로 확장하는 식으로 진행
- 모든 경우에 브로드캐스팅이 되는 것은 아님 
> 확장이 가능한 경우를 확인하는 규칙
- 넘파이 배열의 shape을 우측 정렬하고 각 차원별로 숫자를 비교
- 비교하는 모든 차원이 두 조건 중 하나에 충족되어야 함
- 해당 차원 간의 숫자가 동일하거나, 해당 차원 중 하나가 1인 경우
- ex) 3x4x5 / 4x1 -> 3x4x5 로 확장
- ex) 3x4x5 / 3x2 -> 불가능

In [438]:
#배열과 스칼라 값이 연산에서 결합될 때 
a=np.array([1.0,2.0,3.0])
b=2.0
a*b

array([2., 4., 6.])

In [439]:
x=np.arange(5)
print(x)
y=np.ones_like(x)
print(y)
print(x+y)
print(x+1)

[0 1 2 3 4]
[1 1 1 1 1]
[1 2 3 4 5]
[1 2 3 4 5]


## 차원 축소 연산
- 하나의 행에 있는 원소들을 하나의 데이터 집합으로 보고 그 집합의 평균을 구하면 각 행에 대해 하나의 숫자가 나오게 됨
- 예를 들어 (10,5) 크기의 2차원 배열에 대해 행-평균을 구하면 10개의 숫자를 가진 1차원 벡터가 나오게 됨
- 이러한 연산을 차원 축소(dimension reduction) 연산이라고 함
> 축소 연산 메서드
- 최대/최소: min, max, argmin, argmax
- 통계: sum, mean, median, std, var
- 불리언: all, any

### sum()
- 해당 배열의 합산 결과를 반환
- 연산 대상이 2차원 이상일 때에는 axis 키워드 인수를 사용
- 2차원일 경우 axis=0은 행 간(세로)의 연산 / axis=1은 열 간(가로)의 연산

In [328]:
x=np.array([1,2,3,4])
print(np.sum(x))
print(x.sum())

10
10


In [327]:
x=np.arange(12).reshape(3,-1)
print(x)
print(x.sum(axis=0)) 
print(x.sum(axis=1))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[12 15 18 21]
[ 6 22 38]


### min() / max()
- 해당 배열의 가장 작은(큰) 값의 결과를 반환
- 연산 대상이 2차원 이상일 때에는 axis 키워드 인수를 사용 (2차원 일때 axis=0- 행, 1- 열 // 3차원 일때 axis=0- 깊이, 1- 행, 2-열)


In [329]:
x=np.arange(20).reshape(2,5,-1)
x

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]]])

In [330]:
x.min()

0

In [331]:
np.min(x)

0

In [332]:
x.min(axis=0)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [333]:
np.min(x,axis=1)

array([[ 0,  1],
       [10, 11]])

In [334]:
x.min(axis=2)

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18]])

### argmin() / argmax()
- 해당 배열의 제일 작은(큰) 값의 **인덱스**를 반환
- 연산 대상이 2차원 이상일 때에는 axis 키워드 인수를 사용

In [335]:
x=np.arange(20).reshape(2,5,-1)
x

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]]])

In [336]:
x.argmin()

0

np.argmin(x)

In [338]:
x.argmin(axis=0)

array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0]], dtype=int64)

In [339]:
np.argmin(x,axis=1)

array([[0, 0],
       [0, 0]], dtype=int64)

In [340]:
np.argmin(x,axis=2)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]], dtype=int64)

### mean(), median(), np.all(), np.any()
- mean(): 평균
- median(): 중앙값
- np.all(): 배열요소가 모두 True이면 True 반환
- np.any(): 배열요소가 하나라도 True면 True 반환

In [341]:
x=np.array([1,2,3,1])

In [342]:
x.mean()

1.75

In [343]:
np.median(x)

1.5

### 연습문제

```
실수로 이루어진 5 x 6 형태의 데이터 행렬을 만들고 이 데이터에 대해 다음과 같은 값을
구한다.
1. 전체의 최대값
2. 행 간의 합
3. 행 간의 최대값
4. 열 간의 평균
5. 열 간의 최소값
```

In [347]:
practice = np.array([[1.1, 7.1, 8.0, 2.1, 6.5, 7.2],
                     [2.7, 5.2, 3.3, 9.0, 7.7, 2.8],
                     [0.7, 8.8, 4.2, 8.9, 4.3, 7.4],
                     [8.2, 1.1, 5.4, 2.9, 6.9, 0.2],
                     [7.4, 4.8, 2.7, 3.1, 2.8, 8.9]])

print(practice.max())
print(practice.sum(axis=0))
print(practice.max(axis=0))
print(practice.mean(axis=1))
print(practice.min(axis=1))

9.0
[20.1 27.  23.6 26.  28.2 26.5]
[8.2 8.8 8.  9.  7.7 8.9]
[5.33333333 5.11666667 5.71666667 4.11666667 4.95      ]
[1.1 2.7 0.7 0.2 2.7]


## 정렬 sort()
- 배열 안의 원소를 크기에 따라 정렬하여 새로운 배열을 만듦
- 2차원 이상인 경우에는 axis 키워드 인수를 사용
- ndarray.sort() 메서드는 **해당 객체의 자료 자체가 변화**하는 자체변화 메서드이므로 사용시 주의!!

In [354]:
a=np.array([[3,2,8,9],
           [5,3,6,2],
           [9,1,8,7]])
print(np.sort(a,axis=1))
print(np.sort(a,axis=0))

[[2 3 8 9]
 [2 3 5 6]
 [1 7 8 9]]
[[3 1 6 2]
 [5 2 8 7]
 [9 3 8 9]]


### argsort()
- 오름차순대로의 인덱스 순서를 가져옴

In [355]:
a=np.array([42,38,12,25])
j=np.argsort(a)
j

array([2, 3, 1, 0], dtype=int64)

a[j]

In [357]:
a[[2,3,1,0]]

array([12, 25, 38, 42])

## 고급 인덱싱

### 연습문제

In [395]:
scores=np.array([[1,  2,  3,  4],
                [46, 99, 100, 71],
                [81, 59, 90, 100]])
eng_ranking=np.argsort(scores[1,:])
eng_ranking

array([0, 3, 1, 2], dtype=int64)

In [396]:
scores[:,eng_ranking]

array([[  1,   4,   2,   3],
       [ 46,  71,  99, 100],
       [ 81, 100,  59,  90]])

## 기술 통계
### 표본평균: 표본들의 평균 
### 표본분산: 표본들이 표본평균과 떨어져 있는 정도
### 표준편차: 표본 분산의 양의 제곱근 값 
### 사분위수: percentile(array,percent)

## 난수 발생과 카운팅
- Numpy의 random 서브패키지 (표준 라이브러리인 random과 다름)

### 시드 설정하기
- seed 인수로는 0과 같거나 큰 정수를 넣어줌

In [399]:
np.random.seed(0)
# rand 함수는 0~1 사이의 난수 발생
np.random.rand(5)

array([0.5488135 , 0.71518937, 0.60276338, 0.54488318, 0.4236548 ])

In [400]:
np.random.rand(10)

array([0.64589411, 0.43758721, 0.891773  , 0.96366276, 0.38344152,
       0.79172504, 0.52889492, 0.56804456, 0.92559664, 0.07103606])

In [401]:
np.random.seed(0)

In [402]:
np.random.rand(5)

array([0.5488135 , 0.71518937, 0.60276338, 0.54488318, 0.4236548 ])

In [403]:
np.random.rand(10)

array([0.64589411, 0.43758721, 0.891773  , 0.96366276, 0.38344152,
       0.79172504, 0.52889492, 0.56804456, 0.92559664, 0.07103606])

### 데이터의 순서 바꾸기
- shuffle()
- 자체 변환(in-place)함수로 한 번 사용하면 변수의 값이 바뀜

#### 데이터 샘플링
- 표본에서 일부를 무작위로 선택하는 것을 sampling이라고 함
- choice()
> numpy.random.choice(a, size=None, replace=True, p=None)
- a: 배열이면 원래의 데이터, 정수이면 arange(a) 명령으로 데이터 생성
- size: 정수, 샘플 숫자
- replace: 불리언, True이면 한 번 선택한 데이터를 다시 선택 가능
- p: 배열, 각 데이터가 선택될 수 있는 확률

In [405]:
np.random.choice(5,5,replace=False)

array([2, 4, 3, 0, 1])

In [406]:
np.random.choice(5,3,replace=False)

array([3, 1, 4])

In [408]:
np.random.choice(5,10)

array([3, 3, 0, 1, 1, 1, 0, 2, 4, 3])

In [412]:
np.random.choice(5,10,p=[0.1,0,0.3,0.6,0])

array([2, 3, 2, 2, 2, 2, 2, 2, 3, 3])

### 난수 생성
- rand: 0부터 1사이의 균일 분포
- randn: 표본 정규 분포
- randint: 균일 분포의 정수 난수 

#### rand()

In [413]:
np.random.rand(10)

array([0.61306346, 0.90234858, 0.09928035, 0.96980907, 0.65314004,
       0.17090959, 0.35815217, 0.75068614, 0.60783067, 0.32504723])

In [414]:
np.random.rand(3,5)

array([[0.03842543, 0.63427406, 0.95894927, 0.65279032, 0.63505887],
       [0.99529957, 0.58185033, 0.41436859, 0.4746975 , 0.6235101 ],
       [0.33800761, 0.67475232, 0.31720174, 0.77834548, 0.94957105]])

#### randn()
- 기댓값이 0이고 표준편차가 1인 표준 정규 분포를 따르는 난수를 생성

In [415]:
np.random.randn(10)

array([ 1.50944508,  1.06777513, -0.68658948,  0.01487332, -0.3756659 ,
       -0.03822364,  0.36797447, -0.0447237 , -0.30237513, -2.2244036 ])

#### randint()
> numpy.random.randint(low, high=None, size= None)
- 표준 라이브러리와 다른점: 최댓값 포함을 하지 않음
- high를 입력하지 않으면 0과 low 사이의 숫자
- high를 입력하면 low와 high 사이의 숫자

In [416]:
np.random.randint(1,2,100)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

### 연습문제

In [422]:
np.random.seed(0)
side=np.random.randint(0,2,100)

np.mean(side)


0.56

In [425]:
np.random.seed(0)
dice=np.random.randint(1,7,100)
np.mean(dice)

3.42

## 정수 데이터 카운팅
- 난수가 정수값이면 unique 명령이나 bincount 명령으로 데이터 값을 분석 가능
- unique(): 데이터에서 중복된 값을 제거, 중복되지 않는 값의 리스트 출력
- return_counts 인수를 True를 설정하면 각 값의 데이터 개수도 출력
- unique 함수는 데이터에 존재하는 값에 대해서만 개수를 세므로, 특정 범위안의 수인 경우에는 bincount 함수에 minlength 인수를 설정하여 쓰는 것이 더 편리함 
- bincount 함수는 0부터 minlength-1 까지의 숫자에 대해 각각 카운트를 하고, 해당 범위 내 데이터가 없을 경우에는 0으로 카운트함